version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build_backend:
    docker:
      - image: cimg/node:18.20.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: ~/project/Backend
          cache-path: ~/project/Backend/node_modules
          override-ci-command: npm install
      - run:
          name: Build Backend
          command: |
            cd Backend
      - persist_to_workspace:
          root: ~/project
          paths:
            - Backend
  security_test:
    docker:
      - image: cimg/node:18.20.2
        environment:
          NODE_ENV: test
          MONGO_URI: mongodb://localhost:27017/test
          JWT_SECRET: test-secret
          SESSION_SECRET: test-session-secret
      - image: mongo:4.4
        command: mongod --port 27017
    resource_class: medium
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Security Testing Tools
          command: |
            cd Backend
            sudo npm install -g newman
            sudo npm install -g newman-reporter-htmlextra
            sudo npm install -g snyk
            sudo npm install -g artillery
            sudo apt-get update && sudo apt-get install -y nmap
      - run:
          name: Install Backend Dependencies
          command: |
            cd ~/project/Backend
            npm install
      - run:
          name: Start Backend Server
          command: |
            cd ~/project/Backend
            npm run build &
            sleep 10
      - run:
          name: Run Newman Tests
          command: |
            cd ~/project/Backend
            newman run tests/APDS7311.postman_collection.json \
              -e tests/environment.json \
              --reporters cli,htmlextra \
              --reporter-htmlextra-export newman-report.html
      - store_artifacts:
          path: ~/project/Backend/newman-report.html
          destination: newman-reports
      - persist_to_workspace:
          root: ~/project
          paths:
            - Backend/newman-report.html
  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Create SonarQube Configuration
          command: |
            echo "sonar.projectKey=${SONAR_PROJECT_KEY}" > sonar-project.properties
            echo "sonar.organization=${SONAR_ORG}" >> sonar-project.properties
            echo "sonar.host.url=https://sonarcloud.io" >> sonar-project.properties
            echo "sonar.sources=Backend" >> sonar-project.properties
            echo "sonar.tests=Backend/tests" >> sonar-project.properties
            echo "sonar.test.inclusions=Backend/tests/**/*.test.js,Backend/tests/**/*.spec.js" >> sonar-project.properties
            echo "sonar.exclusions=**/build-wrapper-dump.json,Backend/**/node_modules/**,Backend/**/coverage/**,Backend/tests/**/*.json" >> sonar-project.properties
            echo "sonar.javascript.lcov.reportPaths=Backend/coverage/lcov.info" >> sonar-project.properties
            echo "sonar.sourceEncoding=UTF-8" >> sonar-project.properties
      - run:
          name: SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.token=${SONAR_TOKEN} \
              -Dsonar.qualitygate.wait=true
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build_backend
      - security_test:
          requires:
            - build_backend
      - sonarqube
