version: 2.1

orbs:
  node: circleci/node@5.1.0
  newman: postman/newman@1.0.0

jobs:
  security_test:
    docker:
      - image: cimg/node:18.20.2
        environment:
          NODE_ENV: test
          MONGO_URI: mongodb://localhost:27017/test
          JWT_SECRET: test-secret
          SESSION_SECRET: test-session-secret
      - image: mongo:4.4
        command: mongod --port 27017
    resource_class: medium
    steps:
      - checkout
      
      # Install Backend dependencies
      - node/install-packages:
          pkg-manager: npm
          app-dir: ~/project/Backend  # Specify Backend directory
          cache-path: ~/project/Backend/node_modules
          override-ci-command: npm install

      # Install Frontend dependencies
      - node/install-packages:
          pkg-manager: npm
          app-dir: ~/project/Frontend/frontend  # Specify Frontend directory
          cache-path: ~/project/Frontend/frontend/node_modules
          override-ci-command: npm install
      
      # Rest of your security test steps...
      # Make sure to cd into the correct directory before running tests
      - run:
          name: Install Security Testing Tools
          command: |
            cd Backend  # Change to Backend directory
            sudo npm install -g newman
            sudo npm install -g snyk
            sudo npm install -g artillery
            sudo apt-get update && sudo apt-get install -y nmap
