version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build_backend:
    docker:
      - image: cimg/node:18.20.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: ~/project/Backend
          cache-path: ~/project/Backend/node_modules
          override-ci-command: npm install
      - run:
          name: Build Backend
          command: |
            cd Backend
      - persist_to_workspace:
          root: ~/project
          paths:
            - Backend
  security_test:
    docker:
      - image: cimg/node:18.20.2
        environment:
          NODE_ENV: test
          MONGO_URI: mongodb://localhost:27017/test
          JWT_SECRET: test-secret
          SESSION_SECRET: test-session-secret
      - image: mongo:4.4
        command: mongod --port 27017
    resource_class: medium
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Security Testing Tools
          command: |
            cd Backend
            sudo npm install -g newman
            sudo npm install -g snyk
            sudo npm install -g artillery
            sudo apt-get update && sudo apt-get install -y nmap
      - run:
          name: Install Backend Dependencies
          command: |
            cd ~/project/Backend
            npm install
      - run:
          name: Start Backend Server
          command: |
            cd ~/project/Backend
            node index.js &
            sleep 10
      - run:
          name: Run Newman Tests
          command: |
            cd ~/project/Backend
            newman run tests/APDS7311.postman_collection.json -e tests/environment.json
      # Additional security tests can be added here
  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
              -Dsonar.organization=${SONAR_ORG} \
              -Dsonar.sources=Backend \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${SONAR_TOKEN} \
              -Dsonar.exclusions=Backend/**/node_modules/**,Backend/**/test/**,Backend/**/coverage/** \
              -Dsonar.security.additional-tests=true
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - sonarqube
      - build_backend
      - security_test:
          requires:
            - build_backend
